### ISSUE TITLE
Lectures 'Under Development' - Feedback

### ISSUE THREAD

**Issue by brymz** [datacarpentry/semester-biology#421]
No fix
- [x] Consider identifying language of code blocks
- [x] Decide on (aside text) vs. (*aside text*) vs. ( *aside text* ) and make necessary edits
- [x] `_` to `-` in file names. (#429)

Fixed
- [x] `Scientific-shrub-volume-3-R.md`: Item 10 out of list (#423)
- [x] `Version-control-basics-adding-a-remote-R.md`: fix nested list (#423)
- [x] `Graphing-adult-size-vs-newborn-size-1-R.md`: Item 5 'go' -> 'do' (#423)
- [x] `assignments/sql-intro.md`: extra `'Creating Tables'` (#424)
- [x] `Version-control-set-up-git-R.md` duplicate `title` (#425)
- [x] Better introduce `Basic-data-management-review-R.md` to `r-git.md` (#426)
- [x] Add `exercises/` link to `assignments/` (#427)
- [x] `.IPYNB` to `materials/` (#430)
- [x] Check for `.` after follow-up links ( i.e. `'Shrub Volume 3'`) (#432)
